name: RxArrow workflows

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: setup jdk
        uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
      - name: test
        run: ./gradlew check

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: setup jdk
        uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
      - name: build the app
        run: ./gradlew build
